### ISSUE TITLE
Error launching app with space in name

### ISSUE THREAD

**Issue by nikilster** [ios-control/ios-sim#121]
Compiled an .xcworkspace according to: http://king107.blogspot.in/p/how-to-create-simulator-build-and-run.html

`Session could not be started: Error Domain=NSPOSIXErrorDomain Code=22 "Unable to run app in Simulator" UserInfo=0x7fc639e14240 {NSLocalizedFailureReason=An error was encountered while running (Domain = NSPOSIXErrorDomain, Code = 22), NSUnderlyingError=0x7fc639e1ff70 "Installation Failed", NSLocalizedRecoverySuggestion=An error occurred while preparing the app for installation (no bundle identifier was found at the expected path), NSLocalizedDescription=Unable to run app in Simulator}`

Getting this error when I try to install the Release.  The Debug version works fine.  (using these flags to build: http://stackoverflow.com/questions/23482823/creating-an-ios-simulator-build-of-cocoapod-project/26111061#comment37054769_23724107)  Tried a bunch of things and I'm guessing it's because of space in the product name when the bundle identifier has a dash instead of a space?

Thanks for the help!

**Comment by cvarta** [comment]
@m-vdb trying to update the platform threw this error: 

```bash
chriss-mbp:cordova-tutorial chris$ cordova platforms update ios

module.js:340
    throw err;
          ^
Error: Cannot find module 'shelljs'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/chris/.cordova/lib/npm_cache/cordova-ios/3.7.0/package/bin/update:21:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
Error: /Users/chris/.cordova/lib/npm_cache/cordova-ios/3.7.0/package/bin/update: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
chriss-mbp:cordova-tutorial chris$ cordova platform update ios
```
My workaround was to complete remove and re-add the platform:

```
$cordova platform rm ios
$cordova platform add ios
