### ISSUE TITLE
Unable to install the application in simulator

### ISSUE THREAD

**Issue by asadali737** [ios-control/ios-sim#269]
# Issue
I am using following command to install my iOS application in iPhone 11 Pro Max simulator.

`ios-sim install /path-to-application -d iPhone-11-Pro-Max`

And I am getting following error messages.
```
/usr/local/lib/node_modules/ios-sim/src/commands/install.js:21
        throw err
        ^

Error: Invalid binary plist. Expected 'bplist' at offset 0.
    at exports.parseBuffer (/usr/local/lib/node_modules/ios-sim/node_modules/bplist-parser/bplistParser.js:55:11)
    at tryParseBuffer (/usr/local/lib/node_modules/ios-sim/node_modules/bplist-parser/bplistParser.js:28:18)
    at /usr/local/lib/node_modules/ios-sim/node_modules/bplist-parser/bplistParser.js:46:7
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```

# System Specs

System Software Overview:
```
      System Version: macOS 10.15.3 (19D76)
      Kernel Version: Darwin 19.3.0
      Boot Volume: MacOS
      Boot Mode: Normal
      Computer Name: ----
      User Name: ----
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 3 days 15:47
```

ios-sim version: `ios-sim/9.0.0 darwin-x64 node-v12.14.1`

```
Xcode 11.3.1
Build version 11C504
```
Xcode Path: `/Applications/Xcode.app/Contents/Developer`

Node version: `v12.14.1`

**Comment by AmirDoreh** [comment]
did you find any solution for this ? @asadali737

**Comment by NikosVlah** [comment]
Exactly the same error . Any solution for this ?

**Comment by jittuu** [comment]
I fixed it by converting to binary format.

1. Right click on [name].app and click Show Package Contents
2. drag and drop info.plist to another folder (outside of [name].app). (I drop at my home folder [~] on another tab)
3. convert it to binary format `plutil -convert binary1 Info.plist`
4. drag [binary] info.plist into [name].app content.

**Comment by muhammadabbas001** [comment]
When I used the following command
`plutil -convert binary1 Info.plist`
Runs successfully but not convert the file into binary.

**Comment by kanadgodse-lh** [comment]
For me, it converts into bplist binary, and app is also installed in simulator, but when I click to open the app, then it shows black screen and crashes.
